
server:
  port: 10002
spring:
  application:
    name: thirdproject-usermanager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
pagehelper:
#设置数据库方言
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true