

server:
  port: 10001
spring:
  application:
    name: thirdproject-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/captain?characterEncoding=utf-8&serverTimezone=UTC
    password: 123456
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
mybatis:
  type-aliases-package: com.qq.j1902.pojo
  mapper-locations: classpath:mapping/*.xml
pagehelper:
#设置数据库方言
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true
